# Generated by Django 2.0 on 2017-12-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('band_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('albums_num', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'bands',
            },
        ),
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('concert_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'concerts',
            },
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('commercial', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'organizers',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'places',
            },
        ),
    ]
