# Generated by Django 2.0 on 2017-12-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bands',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='concerts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organizers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'managed': True},
        ),
    ]
