# Generated by Django 2.0 on 2017-12-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_auto_20171218_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bands',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='concerts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='organizers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'managed': False},
        ),
    ]
