# Generated by Django 2.0 on 2017-12-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_auto_20171218_1911'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bands',
            table=None,
        ),
    ]
