# Generated by Django 2.0 on 2017-12-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_auto_20171218_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concerts',
            options={'managed': True},
        ),
    ]
