# Generated by Django 2.0 on 2017-12-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0006_auto_20171218_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concerts',
            options={'managed': False},
        ),
    ]
